### ISSUE TITLE
User Search

### ISSUE THREAD

**Issue by LogicPlague** [carlbennett/bnetdocs-web#100]
Should add a way for people to be able to search for users by adding a user search bar or at least an alphabetical search, or even both types.

**Comment by inetknght** [comment]
On the administrative side the feature already exists as much as is needed. On the user-facing side I don't think this is appropriate.

The BnetDocs website goal is to document the network protocols related to Battle.net. Bnetdocs website needs to stay hyper-focused on facts and truthy information about the network protocols related to Battle.net and the games it supports. There's a simple message posting feature for specific packets.

The website won't (and shouldn't) be able to provide a good forum for long-running discussions. Long-running discussions have a habit of getting out of context very quickly. So they shouldn't happen on the website.

There's a [discord server](https://bnetdocs.org/discord) which handles user-to-user comments and discussions. If you have a question for a specific user then you should look for them on Discord. If they're not on that Discord server then it's very likely that they've moved on from BnetDocs related work and you should respect that.
