### ISSUE TITLE
Mobile site

### ISSUE THREAD

**Issue by carlbennett** [carlbennett/bnetdocs-web#17]
Create a mobile version of the entire BNETDocs website. This should not be started until the desktop version has been near or completely finished.

**Comment by carlbennett** [comment]
This is mostly complete as of ac9a6ec769d43cda2ac8ff4b1d4352344261e21a. Work still needs to be done:
- [x] Responsive navigation menu
- ~~Reformatting of some not so mobile-friendly pages, such as the [servers](https://bnetdocs.org/servers) page~~ #50
- [x] Full testing of site via mobile device

**Comment by RElesgoe** [comment]
I think until a mobile version is more functional and implemented, mobile devices should see the desktop site. Currently, going to bnetdocs.org on a mobile device only displays the news, which makes accessing the main part of the website, the packet and document pages, impossible unless the user directly enters in the exact url in his/her web browser.
Also a suggestion for when a mobile version is functional, create an option for mobile devices to view the desktop site by having a link at the bottom of the website.

**Comment by carlbennett** [comment]
Mobile navigation is now implemented as of d68f4f5e330aeaa6fc0119872cf599966f5a5a26 and its UI is now cleaned up as of dd71efd8216cfc95afa3acc82ab8cd503c1d8e43.

**Comment by carlbennett** [comment]
Created issue #50: Improve mobile server list page.
