### ISSUE TITLE
Change Notation Convention Type Names

### ISSUE THREAD

**Issue by RElesgoe** [carlbennett/bnetdocs-web#32]
Use `u8`, `u16`, `u32`, and `u64` instead of `BYTE`, `WORD`, `DWORD`, `QWORD` respectively. This immediately shows the signedness of the type, and does not use implementation-dependent types.

**Comment by carlbennett** [comment]
Many bots and other applications refer to these terms internally and everyone in the community is on the same page as to what these mean. Changing them would require changing them everywhere, not just on BNETDocs, and getting everyone on board.

I'll see about clarifying these terms in the document, but I do not feel that the documentation across the entire site should adopt this standard. It would be nice to disambiguate, but it would be unwelcoming.

**Comment by carlbennett** [comment]
Changes applied:

``` diff
diff --git a/issue32.md b/issue32.md
index 9b46b96..fd01ace 100644
--- a/issue32.md
+++ b/issue32.md
@@ -8,10 +8,10 @@ All numeric Battle.net types are little-endian. Battle.net uses the following ty

 - `STRING` - A null-terminated array of characters. The encoding varies from packet to packet, but generally will either be ISO 8859-1 or less commonly UTF-8.
 - `STRINGLIST` - A series of `STRING` values. This is like an array of `STRING` values in every way, except it is always variable/non-fixed size and terminated by an empty item at the end of the array (or otherwise double null-terminated).
-- `BYTE` - 8 bit (1 byte) unsigned integer.
-- `WORD` - 16 bit (2 byte) unsigned integer.
-- `DWORD` - 32 bit (4 byte) unsigned integer.
-- `QWORD` - 64 bit (8 byte) unsigned integer.
+- `BYTE` - 8 bit (1 byte) unsigned integer, also known as `u8` in C.
+- `WORD` - 16 bit (2 byte) unsigned integer, also known as `u16` in C.
+- `DWORD` - 32 bit (4 byte) unsigned integer, also known as `u32` in C.
+- `QWORD` - 64 bit (8 byte) unsigned integer, also known as `u64` in C.
 - `BOOL` or `BOOLEAN` - An unsigned 8 bit or 32 bit (depending on packet) integer whose value is always 0 (FALSE) or 1 (TRUE).
 - `VOID` - Data marked as `VOID` has no particular type or length. Where data is marked as `VOID`, additional information is given on its use.
 - `FILETIME` - A [Windows struct](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724284(v=vs.85).aspx), used to store filetime information. It can be read as a `QWORD` or two `DWORD`s.
```

**Comment by RElesgoe** [comment]
> Many bots and other applications refer to these terms internally and everyone in the community is on the same page as to what these mean.

The types are equivalent, so it shouldn't matter to other people that the names are changed. It has the benefit of being more easily identifiable and conveys information better.

> Changing them would require changing them everywhere, not just on BNETDocs, and getting everyone on board.

I don't believe so, unless other programs or websites are actually scraping BNETDocs and parsing the text for some reason, which I do not believe is happening. Again, the types are equivalent, so other programs and websites have the option of either changing the name or not changing the name, and it won't matter.

> Changes applied

`u8`, `u16`, `u32`, and `u64` aren't actually the real names in C and C++, they're `uint8_t`, `uint16_t`, `uint32_t`, and `uint64_t`. I suggested the former so that the names are language agnostic as well.

**Comment by carlbennett** [comment]
> `u8`, `u16`, `u32`, and `u64` aren't actually the real names in C and C++, they're `uint8_t`, `uint16_t`, `uint32_t`, and `uint64_t`. I suggested the former so that the names are language agnostic as well.

You're wrong. http://stackoverflow.com/questions/30896489/why-is-u8-u16-u32-u64-used-instead-of-unsigned-int-in-kernel-programming

**Comment by RElesgoe** [comment]
`u8`, `u16`, `u32`, and `u64` are typedefs in the Linux kernel, and commonly typedef'd in many other codebases, but they're not names as defined by the C and C++ standards.
http://en.cppreference.com/w/cpp/header/cstdint

**Comment by carlbennett** [comment]
Not just the Linux kernel, a lot of C projects use it.

Point is, there's ambiguity with names of types and this is what the community uses. **Your request is denied and that's final.**
