### ISSUE TITLE
Short packet description on the packet index page

### ISSUE THREAD

**Issue by RElesgoe** [carlbennett/bnetdocs-web#36]
When searching for a packet which you know the function of, but do not know the name or ID, it would be useful to have a short description under every packet in the packet index.

**Comment by carlbennett** [comment]
This is certainly doable using the `Common::stripUpTo` function, I will look into adding it now.

**Comment by carlbennett** [comment]
Resolved in d544b93de3e6568d4b4ef53d8b4f7e8a0b70215c
