### ISSUE TITLE
Implement packet creator

### ISSUE THREAD

**Issue by carlbennett** [carlbennett/bnetdocs-web#46]

**Comment by dzik87** [comment]
Any progress on this feature ? i have some d2gs packets what can be added/updated

**Comment by carlbennett** [comment]
No progress has been made to this feature. Progress to this project has been slow since myself and others are focused on other matters.

If you message me on Discord, I can help get the packets added for you. My Discord user is `Caaaaarrrrlll#1337` or you can find me and other BNETDocs maintainers on the [BNETDocs Discord](https://bnetdocs.org/discord).

**Comment by carlbennett** [comment]
This has been implemented as of 585f658042156454686ab28d335591e3072ea530.
