### ISSUE TITLE
When editing packets or documents, comments should be available at the bottom

### ISSUE THREAD

**Issue by nmbook** [carlbennett/bnetdocs-web#73]
Maybe read-only or something, but always writable/editable/deletable if permissions/etc, if that workflow makes sense.

That way, when you are making changes you can be aware of what people have said without having to go back to the previous page.

**Comment by carlbennett** [comment]
This has been implemented in the latest version of the code as of 4c31d5dd03a67b467086dcb648e28a0fdac9f78c.
