### ISSUE TITLE
Modify documents and packets tables to include short description

### ISSUE THREAD

**Issue by carlbennett** [carlbennett/bnetdocs-web#84]
Short description could be used on the document and packet index pages instead of deriving them from the document/packet's first sentence.

**Comment by nmbook** [comment]
This is the same for documents too. I thought it was intended?

**Comment by carlbennett** [comment]
We should include documents while implementing this feature.

**Comment by carlbennett** [comment]
We could also make it used the derived value if there's no short description.

**Comment by carlbennett** [comment]
Another flag could be added to the options bitmask that allows specifying whether to allow an empty short description, or to deny an empty short description and instead derive the value.

**Comment by carlbennett** [comment]
Thoughts?

**Comment by nmbook** [comment]
Would this options bitmask be per packet? If you mean something per packet, wouldn't it make more sense to just have the field be nullable? If present and non-empty, use it. Otherwise, use current generated value.

**Comment by carlbennett** [comment]
This has been implemented as of 232be88ae19b06dae367bf88c6f3b278f460bccc.
